### ISSUE TITLE
SDecodingError

### ISSUE THREAD

**Issue by lishuailibertine** [tesseract-one/Substrate.swift#3]
Hello, I used the 'Polkadot< httprcclient >.create' call,   I encountered an error while using the SDK to get user information：

error description: error: decoding(error: ScaleCodec.SDecodingError.dataCorrupted(ScaleCodec.SDecodingError.Context(path: ["RuntimeVersionedMetadata"], debugDescription: "Unsupported metadata version 13")))

**Comment by ypopovych** [comment]
Yep. We will need to add metadata v13. We are working on this library, it doesn't have all API types implemented yet. We will add everything in a couple of weeks.

**Comment by lishuailibertine** [comment]
> Yep. We will need to add metadata v13. We are working on this library, it doesn't have all API types implemented yet. We will add everything in a couple of weeks.

ok, hope can use it soon 😁

**Comment by ypopovych** [comment]
Pushed new updated version. Should work now
