### ISSUE TITLE
Strange conversion from public key to SS58 for .polkadot

### ISSUE THREAD

**Issue by frameorigin** [tesseract-one/Substrate.swift#7]
**Issue**
When I try to convert a public key to an SS58 address for the polkadot network, I am getting the wrong address that I expect.

**How to reproduce**
```swift
let publicKey = anySr25519PublicKey // or anyEd25519PublicKey
print(publicKey.ss58(format: .polkadot))
```

**Data to reproduce the issue**
public key hex: 0x6c13537af75e5a3b724db7334798f9084c192a2896e0c68a4216151b8e29bb32
expected value: 13Shuvyj3DDekCNbeamVMPKn5WBmGqW2Vj4Cf4rCi2pdHGZc
actual value: 1Z76ec4BUEjzN9yLPc15csUS35hquDvMZBhFWsa1gqQB2i

**Comment by ypopovych** [comment]
Fixed in the new version. Bug in Base58 encoder
