### ISSUE TITLE
Substrate client init error

### ISSUE THREAD

**Issue by abhishekCO2** [tesseract-one/Substrate.swift#9]
trying to connect to our substrate based server, got error below
```
        do {
            let substrate = try await Api(
                rpc: JsonRpcClient(.ws(url: nodeUrl)),
                config: .dynamicBlake2
            )
        } catch {
            print("testRPC :: ERROR:: ", error)
        }
```

```
Metadata RPC Call fallback: reply(method: "state_call", params: (Metadata_metadata_versions, 0 bytes, nil), error: JsonRPC.ResponseError<Serializable.AnyValue>(code: -32603, message: "Unknown error occurred", data: Optional("Client(Execution(Wasmi(Function("Module doesn\'t have export Metadata_metadata_versions"))))")))
testRPC :: ERROR::  dataCorrupted(ScaleCodec.DecodingError.Context(path: ["VersionedNetworkMetadata"], debugDescription: "Unsupported metadata version 12"))
```

**Comment by ypopovych** [comment]
Metadata v12 is not supported. Only v14 and v15

**Comment by abhishekCO2** [comment]
@ypopovych : What's the alternate then?

**Comment by abhishekCO2** [comment]
can you recommend any other client which still supports same?

**Comment by ypopovych** [comment]
Could you try to search on the substrate site for other clients? Metadata < v14 doesn't have a lot of info and libraries should load types from JSON files. In this library we switched to the new type system in the metadata v14+

**Comment by srv-rits** [comment]
Do you have the old files for metadata v12?
Might try using those for our chain @ypopovych

**Comment by ypopovych** [comment]
@srv-rits unfortunately no. This library started with v13 metadata and we switched to the better v14 metadata halfway through development.

**Comment by srv-rits** [comment]
Is it possible to create a signed transaction payload without the use of metadata? @ypopovych
